# Generated by Django 5.2 on 2025-05-06 02:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gestao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_cliente_cpf_alter_cliente_telefoe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefoe',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=0, max_length=11, validators=[gestao.models.validate_phone], verbose_name='Telefone (apenas números)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_validade',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Validade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20, verbose_name='Status do Orçamento'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Placa (sem hífen)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[gestao.models.validate_cpf], verbose_name='CPF (apenas números)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='gestao.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='foi_pago',
            field=models.BooleanField(default=False, verbose_name='Foi Pago?'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('outro', 'Outro')], default='pix', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='gestao.veiculo', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='gestao.cliente', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(choices=[('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('toyota', 'Toyota'), ('hyundai', 'Hyundai')], max_length=50, verbose_name='Marca do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='motor',
            field=models.CharField(max_length=50, verbose_name='Motor'),
        ),
    ]
