from django.db import models


class Cliente(models.Model):
    nome = ...
    cpf = ...
    endereco = ...
    telefoe = ...
    data_nascimento = ...
    veiculo = ...


class Veiculo(models.Model):
    cliente = ...
    marca = ...
    modelo = ...
    ano = ...
    motor = ...


class Orcamento(models.Model):
    cliente = ...
    veiculo = ...
    valor = ...
